const WHATSAPP='5577974003010';const sizes={P:{fatias:4,max:1},M:{fatias:6,max:2},G:{fatias:8,max:2},F:{fatias:12,max:3}};
const products=[['Caipira','Molho de tomate, queijo, frango, requeijão, milho, bacon e orégano','salgadas',{P:39.99,M:50.99,G:60.99,F:70.99}],['Baiana','Molho de tomate, queijo, calabresa, cebola, ovo e pimenta calabresa','salgadas',{P:30.99,M:40.99,G:50.99,F:60.99}],['Bacon','Molho de tomate, queijo, bacon, cebola e orégano','salgadas',{P:30.99,M:40.99,G:50.99,F:60.99}],['4 Queijos','Queijo, provolone, requeijão, gorgonzola e orégano','salgadas',{P:34.99,M:45.99,G:55.99,F:65.99}],['Carne Seca','Queijo, carne seca, cebola e orégano','salgadas',{P:35.99,M:45.99,G:55.99,F:65.99}],['Atum','Queijo, atum, cebola e orégano','salgadas',{P:29.99,M:40.99,G:50.99,F:60.99}],['Lombinho','Queijo e lombo canadense','salgadas',{P:39.99,M:50.99,G:60.99,F:70.99}],['Milho','Queijo, milho, cebola e orégano','salgadas',{P:25.99,M:35.99,G:45.99,F:55.99}],['Calabresa','Queijo, calabresa, cebola e orégano','salgadas',{P:25.99,M:35.99,G:45.99,F:55.99}],['Portuguesa','Queijo, presunto, ervilha, ovo e cebola','salgadas',{P:30.99,M:40.99,G:50.99,F:60.99}],['Frango com Catupiry','Queijo, frango e requeijão cremoso','salgadas',{P:30.99,M:40.99,G:50.99,F:60.99}],['Muçarela','Queijo, tomate e orégano','salgadas',{P:25.99,M:35.99,G:45.99,F:55.99}],['Banana Nevada','Banana, chocolate branco e canela','doces',{P:30.99,M:40.99,G:50.99,F:60.99}],['Romeu e Julieta','Queijo e goiabada','doces',{P:25.99,M:35.99,G:45.99,F:55.99}],['Dois Amores','Chocolate e chocolate branco','doces',{P:30.99,M:40.99,G:50.99,F:60.99}],['Brigadeiro','Chocolate e granulado','doces',{P:25.99,M:35.99,G:45.99,F:55.99}],['Coca Litro','Bem gelada','bebidas',12],['Coca Litro Zero','Bem gelada','bebidas',12],['Guaraná Litro','Bem gelado','bebidas',10],['Coca Lata','Bem gelada','bebidas',6],['Guaraná Lata','Bem gelado','bebidas',5],['Guaraná Litro Zero','Bem gelado','bebidas',10],['Suco Natural','Sabores disponíveis — consultar','bebidas',12]];
products.forEach((p,i)=>p.unshift(i+1));
const money=v=>v==null?'—':v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const comboPrices={P:33.99,M:45.99,G:55.99,F:65.99};
const sizeNames={P:'Pequena',M:'Média',G:'Grande',F:'Família'};
const promoFlavors=['Calabresa','Milho','Mussarela','Brigadeiro','Presunto','Dois Amores','Calabresa com Milho'];
const borderPrices={P:6,M:8,G:10,F:12};
const borders=['Cheddar','Catupiry','Chocolate','Chocolate branco'];
const fillings=[['Calabresa','100 g',6],['Mussarela/Queijo','150 g',8],['Frango','150 g',8],['Catupiry','150 g',10],['Cheddar','150 g',10],['Carne','100 g',10],['Bacon','100 g',10],['Milho','200 g',5],['Cebola','100 g',3],['Tomate','100 g',3],['Azeitona','Porção',3]];
const literDrinks=products.filter(p=>p[3]=='bebidas'&&p[1].includes('Litro')&&!p[1].startsWith('Coca'));
const productsEl=document.getElementById('products'),desktopCart=document.getElementById('desktop-cart'),categories=document.getElementById('categories'),overlay=document.getElementById('overlay');
let category='salgadas',cart=[],selected={},draft=null,modalType=null,lastFocus=null;
const CART_STORAGE_KEY='santi-pizza:cart:v1';
const PIX_KEY='elyonardob@gmail.com';
const checkout={mode:'entrega',payment:'pix',name:'',phone:'',address:'',change:'',note:''};
// Salva apenas o carrinho; os dados pessoais do formulário não são persistidos.
function saveCart(){try{if(cart.length)localStorage.setItem(CART_STORAGE_KEY,JSON.stringify({version:1,items:cart}));else localStorage.removeItem(CART_STORAGE_KEY)}catch(error){/* O pedido continua utilizável quando o armazenamento está indisponível. */}}
function restoreCart(){try{const saved=JSON.parse(localStorage.getItem(CART_STORAGE_KEY));if(saved?.version!==1||!Array.isArray(saved.items))return;const flavorNames=products.filter(p=>typeof p[4]=='object').map(p=>p[1]);cart=saved.items.filter(x=>{if(!x||!Number.isInteger(x.qty)||x.qty<1||!Number.isFinite(x.base)||x.base<0)return false;if(x.type=='drink')return products.some(p=>p[3]=='bebidas'&&p[1]==x.name&&p[4]==x.base);if(!['pizza','combo'].includes(x.type)||!sizes[x.size]||x.name!=(x.type=='combo'?'Combo Pizza ':'Pizza ')+sizeNames[x.size])return false;if(!Array.isArray(x.flavors)||!x.flavors.length||x.flavors.length>sizes[x.size].max||!x.flavors.every(f=>(x.type=='combo'?promoFlavors:flavorNames).includes(f)))return false;if(!['',...borders].includes(x.border)||!Array.isArray(x.extras)||!x.extras.every(e=>Number.isInteger(e)&&!!fillings[e]))return false;if(x.type=='combo')return x.base==comboPrices[x.size]&&literDrinks.some(p=>p[1]==x.drink);return x.base==Math.max(...x.flavors.map(f=>products.find(p=>p[1]==f)[4][x.size]))});}catch(error){cart=[]}}
async function copyPix(button){let copied=false;try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(PIX_KEY);copied=true}}catch(error){}if(!copied){const input=document.createElement('textarea');input.value=PIX_KEY;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();try{copied=document.execCommand('copy')}catch(error){}input.remove();button.focus()}const status=button.parentElement.querySelector('.pix-status');status.textContent=copied?'Chave Pix copiada!':'Não foi possível copiar automaticamente. Selecione a chave acima e copie.';}
function itemPrice(item){return item.base+(item.border?borderPrices[item.size]:0)+(item.extras||[]).reduce((sum,e)=>sum+fillings[e][2],0)}
function totals(){const subtotal=cart.reduce((s,x)=>s+itemPrice(x)*x.qty,0),included=cart.some(x=>x.type=='combo'),fee=checkout.mode=='entrega'&&cart.length&&!included?4:0;return {subtotal,included,fee,total:subtotal+fee}}
function itemDetails(x){return [x.flavors?.join(' + '),x.drink?'🥤 '+x.drink:null,x.border?'Borda: '+x.border:null,...(x.extras||[]).map(i=>'Adicional: '+fillings[i][0]),x.type=='combo'?'Entrega inclusa':null].filter(Boolean)}
function itemSignature(x){const {qty,...value}=x;return JSON.stringify(value)}
function addItem(item){const match=cart.find(x=>itemSignature(x)==itemSignature(item));if(match)match.qty+=item.qty;else cart.push(item);render()}
function changeQty(index,delta){cart[index].qty+=delta;if(cart[index].qty<=0)cart.splice(index,1);render()}
function renderNav(){categories.innerHTML=[['salgadas','🍕 Pizza Salgada'],['doces','🍫 Pizza Doce'],['bebidas','🥤 Bebidas'],['combos','🎁 Combos'],['adicionais','➕ Adicionais']].map(([id,label])=>`<button class="${category==id?'active':''}" aria-pressed="${category==id}" onclick="changeCategory('${id}')">${label}</button>`).join('')}
function changeCategory(id){category=id;render()}
function render(){renderNav();if(category=='combos')productsEl.innerHTML=comboCards();else if(category=='adicionais')productsEl.innerHTML=additionalCards();else productsEl.innerHTML=(category!='bebidas'?`<button class="builder" onclick="builder()"><strong>🍕 MONTE SUA PIZZA</strong><small>Escolha o tamanho, os sabores e a borda</small><span class="builder-cta">CLIQUE AQUI</span></button>`:'')+products.filter(p=>p[3]==category).map(card).join('');renderCart()}
function card(p){const pizza=typeof p[4]=='object',s=selected[p[0]]||'M',price=pizza?p[4][s]:p[4];return `<article class="card"><h3>${p[1]}</h3><p>${p[2]}</p>${pizza?`<div class="sizes">${Object.keys(sizes).map(x=>`<button class="size ${s==x?'active':''}" aria-label="Pizza ${sizeNames[x]}" onclick="selected[${p[0]}]='${x}';render()">${x}</button>`).join('')}</div>`:''}<div class="row"><span class="price">${money(price)}</span><button class="add" onclick="${pizza?`builder('pizza','${s}',${p[0]})`:`addDrink(${p[0]})`}">${pizza?'Escolher pizza':'＋ adicionar'}</button></div></article>`}
function addDrink(id){const p=products.find(x=>x[0]==id);addItem({type:'drink',name:p[1],base:p[4],qty:1})}
function comboCards(){return `<div class="section-intro"><h2>🎁 Combos</h2><p>Pizza + 1 refrigerante de 1 litro + entrega inclusa.</p><p>❤️💛 Sabores promocionais: ${promoFlavors.join(' · ')}.</p></div>`+Object.keys(sizes).map(s=>`<article class="card combo-card"><span class="badge">ENTREGA INCLUSA</span><h3>Combo Pizza ${sizeNames[s]}</h3><p>Pizza ${sizeNames[s].toLowerCase()} com até ${sizes[s].max} ${sizes[s].max==1?'sabor promocional':'sabores promocionais'} + 1 refrigerante de 1 litro.</p><div class="row"><strong class="price">${money(comboPrices[s])}</strong><button class="add" onclick="builder('combo','${s}')">Montar combo</button></div></article>`).join('')}
function additionalCards(){return `<div class="section-intro"><h2>🧀 Adicionais de recheio</h2><p>Escolha o adicional e a pizza do seu pedido que vai recebê-lo.</p></div>`+fillings.map(([name,portion,price],i)=>`<article class="card extra-card"><h3>${name}</h3><p>${portion||'Adicional de recheio'}</p><div class="row"><strong class="price">${money(price)}</strong><button class="add" onclick="chooseTarget('extra',${i})">＋ adicionar</button></div></article>`).join('')+`<div class="section-intro"><h2>🍕 Adicional de borda</h2><p>O valor acompanha o tamanho da pizza: P ${money(6)} · M ${money(8)} · G ${money(10)} · F ${money(12)}.</p></div>`+borders.map((name,i)=>`<article class="card extra-card"><h3>${name}</h3><p>Borda recheada · selecione uma pizza do pedido.</p><button class="add" onclick="chooseTarget('border',${i})">Escolher pizza</button></article>`).join('')}
function openModal(type,html){if(overlay.classList.contains('hidden'))lastFocus=document.activeElement;modalType=type;overlay.innerHTML=`<div class="modal ${type=='builder'?'pizza-builder-modal':''}" role="dialog" aria-modal="true" aria-label="${type=='cart'?'Seu pedido':type=='builder'?'Montar pizza':'Escolher pizza'}"><button class="close modal-close" aria-label="Fechar" onclick="closeModal()">×</button>${html}</div>`;overlay.classList.remove('hidden');document.body.style.overflow='hidden';overlay.querySelector('.close').focus()}
function closeModal(){overlay.classList.add('hidden');overlay.innerHTML='';modalType=null;document.body.style.overflow='';lastFocus?.focus()}
function builder(type='pizza',size='M',id=null){draft={type,size,flavors:id?[id]:[],border:'',drink:'',extras:[]};openModal('builder',`<h2>${type=='combo'?'MONTE SEU COMBO':'MONTE SUA PIZZA'}</h2><p>1. TAMANHO</p><div class="sizes" id="builder-sizes"></div><p>2. SABORES <span id="builder-count"></span></p><small id="flavor-note"></small><div class="flavors" id="flavors"></div><p>3. BORDA</p><div id="border-options" class="option-grid"></div>${type=='combo'?`<p>4. REFRIGERANTE DE 1 LITRO</p><select id="combo-drink" aria-label="Refrigerante do combo" onchange="draft.drink=this.value;updateBuilderPrice()"><option value="">Escolha seu refrigerante</option>${literDrinks.map(p=>`<option>${p[1]}</option>`).join('')}</select><small>Refrigerante e entrega inclusos no valor do combo.</small>`:''}<div class="builder-footer"><div class="row"><b>Total da ${type=='combo'?'oferta':'pizza'}</b><strong id="builder-price"></strong></div><button class="send" id="builder-add" onclick="finishBuilder()">Adicionar ao pedido</button></div>`);renderBuilder()}
function setBuilderSize(size){draft.size=size;draft.flavors=draft.flavors.slice(0,sizes[size].max);renderBuilder()}
function renderBuilder(){const {size,type,flavors}=draft,max=sizes[size].max;document.getElementById('builder-sizes').innerHTML=Object.keys(sizes).map(s=>`<button class="size ${s==size?'active':''}" onclick="setBuilderSize('${s}')">${s} · ${sizes[s].fatias} fatias</button>`).join('');document.getElementById('builder-count').textContent=`(${flavors.length}/${max})`;document.getElementById('flavor-note').textContent=type=='combo'?'Escolha entre os sabores promocionais abaixo.':'Combine sabores salgados e doces. Vale o preço do sabor mais caro.';const list=type=='combo'?promoFlavors.map((name,i)=>({id:i,name})):products.filter(p=>typeof p[4]=='object').map(p=>({id:p[0],name:p[1],price:p[4][size]}));document.getElementById('flavors').innerHTML=list.map(p=>`<button class="${flavors.includes(p.id)?'selected':''}" aria-pressed="${flavors.includes(p.id)}" ${!flavors.includes(p.id)&&flavors.length>=max?'disabled':''} onclick="toggleFlavor(${p.id})"><span>${flavors.includes(p.id)?'✓ ':''}${p.name}</span>${p.price?`<span>${money(p.price)}</span>`:''}</button>`).join('');document.getElementById('border-options').innerHTML=['',...borders].map((name,i)=>`<button class="border-option ${draft.border==name?'selected':''}" aria-pressed="${draft.border==name}" onclick="draft.border=${i?`borders[${i-1}]`:"''"};renderBuilder()"><span>${name||'Sem borda recheada'}</span><strong>${name?'+ '+money(borderPrices[size]):'Sem acréscimo'}</strong></button>`).join('');updateBuilderPrice()}
function toggleFlavor(id){if(draft.flavors.includes(id))draft.flavors=draft.flavors.filter(x=>x!=id);else if(draft.flavors.length<sizes[draft.size].max)draft.flavors.push(id);renderBuilder()}
function draftItem(){const combo=draft.type=='combo',ps=combo?[]:draft.flavors.map(id=>products.find(p=>p[0]==id));return {type:draft.type,name:combo?'Combo Pizza '+sizeNames[draft.size]:'Pizza '+sizeNames[draft.size],size:draft.size,flavors:combo?draft.flavors.slice().sort((a,b)=>a-b).map(i=>promoFlavors[i]):ps.sort((a,b)=>a[0]-b[0]).map(p=>p[1]),base:combo?comboPrices[draft.size]:Math.max(0,...ps.map(p=>p[4][draft.size])),border:draft.border,extras:[],...(combo?{drink:draft.drink}:{}),qty:1}}
function updateBuilderPrice(){document.getElementById('builder-price').textContent=draft.flavors.length?money(itemPrice(draftItem())):'Escolha os sabores';document.getElementById('builder-add').disabled=!draft.flavors.length||(draft.type=='combo'&&!draft.drink)}
function finishBuilder(){if(!draft.flavors.length||draft.flavors.length>sizes[draft.size].max||(draft.type=='combo'&&!draft.drink))return;const item=draftItem();closeModal();addItem(item)}
function chooseTarget(kind,id){const pizzas=cart.map((x,i)=>({x,i})).filter(({x})=>x.size);openModal('target',`<h2>${kind=='border'?'ADICIONAR BORDA':'ADICIONAR RECHEIO'}</h2><p>${kind=='border'?borders[id]:fillings[id][0]} · Escolha a pizza</p>${pizzas.length?`<small>Aplicado a uma unidade da pizza escolhida.${kind=='border'?' Se já houver borda, ela será substituída.':''}</small><div class="flavors">${pizzas.map(({x,i})=>`<button onclick="attachAdditional(${i},'${kind}',${id})"><span>${x.name}<br>${x.flavors.join(' + ')}${x.border?'<br>Borda atual: '+x.border:''}${x.extras.length?'<br>Adicionais: '+x.extras.map(e=>fillings[e][0]).join(', '):''}</span><strong>${kind=='border'?(x.border?'Nova borda: ':'+ ')+money(borderPrices[x.size]):'+ '+money(fillings[id][2])}</strong></button>`).join('')}</div>`:`<p>Adicione uma pizza ou combo ao pedido primeiro. Depois, volte aqui para escolher o adicional.</p><button class="send" onclick="builder()">Montar uma pizza</button>`}`)}
function attachAdditional(index,kind,id){const original=cart[index];if(!original?.size)return;const item={...original,flavors:[...original.flavors],extras:[...original.extras],qty:1};if(kind=='border')item.border=borders[id];else item.extras.push(id);original.qty--;if(!original.qty)cart.splice(index,1);closeModal();addItem(item)}
function renderCart(){saveCart();const t=totals();desktopCart.innerHTML=ticket(t);document.getElementById('cart-count').textContent=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('top-cart-count').textContent=cart.reduce((s,x)=>s+x.qty,0);document.getElementById('open-cart-top').setAttribute('aria-label','Abrir carrinho: '+cart.reduce((s,x)=>s+x.qty,0)+' itens');document.getElementById('mobile-total').textContent=money(t.total);if(modalType=='cart')overlay.querySelector('.cart-content').innerHTML=ticket(t)}
function ticket(t){return `<div class="ticket"><h2>SEU PEDIDO</h2><div class="ticket-list">${cart.length?cart.map((x,i)=>`<div class="ticket-item"><div><strong>${x.qty}x ${x.name}</strong>${itemDetails(x).map(d=>`<small>${escapeHTML(d)}</small>`).join('')}<div class="step"><button aria-label="Diminuir quantidade de ${x.name}" onclick="changeQty(${i},-1)">−</button><span>${x.qty}</span><button aria-label="Aumentar quantidade de ${x.name}" onclick="changeQty(${i},1)">＋</button></div></div><span>${money(itemPrice(x)*x.qty)}</span></div>`).join(''):'<small>Seu carrinho está vazio.</small>'}</div><div class="row"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div>${checkout.mode=='entrega'&&cart.length?`<div class="row"><span>Entrega</span><strong>${t.included?'Inclusa no combo':money(t.fee)}</strong></div>`:''}<div class="row"><b>TOTAL</b><strong class="ticket-total">${money(t.total)}</strong></div>${form()}</div>`}
function field(id,label,extra=''){return `<label class="field-label">${label}<input data-field="${id}" value="${escapeHTML(checkout[id])}" ${extra} oninput="checkout['${id}']=this.value"></label>`}
function form(){return `<div class="mode"><button class="${checkout.mode=='entrega'?'active':''}" onclick="setMode('entrega')">Entrega</button><button class="${checkout.mode=='retirada'?'active':''}" onclick="setMode('retirada')">Retirada</button></div>${field('name','Seu nome','autocomplete="name"')}${field('phone','Telefone','type="tel" autocomplete="tel"')}${checkout.mode=='entrega'?field('address','Endereço para entrega','autocomplete="street-address"'):''}<label class="field-label">Forma de pagamento<select class="payment-select" onchange="checkout.payment=this.value;renderCart()">${[['pix','📱 Pix'],['dinheiro','💵 Dinheiro'],['cartao','💳 Cartão']].map(([v,l])=>`<option value="${v}" ${checkout.payment==v?'selected':''}>${l}</option>`).join('')}</select></label>${checkout.payment=='pix'?`<div class="pix-box"><span>Chave Pix</span><strong class="pix-key">${PIX_KEY}</strong><button class="copy-pix" onclick="copyPix(this)">📋 Copiar chave Pix</button><small class="pix-status" role="status" aria-live="polite"></small></div>`:''}${checkout.payment=='dinheiro'?field('change','Troco para','placeholder="Ex.: 50,00" inputmode="decimal"')+'<small>Deixe em branco se não precisar de troco.</small>':''}<label class="field-label note-label">😊 Deixe um recado!<textarea class="order-note" rows="3" placeholder="Ex.: Sem cebola, por favor. (Opcional)" oninput="checkout.note=this.value">${escapeHTML(checkout.note)}</textarea></label><button class="send whatsapp-send" onclick="send()" ${!cart.length?'disabled':''}>Enviar pedido pelo WhatsApp</button>`}
function setMode(mode){checkout.mode=mode;renderCart()}
function orderMessage(){
 const initial=value=>value.trim().replace(/^./u,c=>c.toLocaleUpperCase('pt-BR'));
 const t=totals(),payment={pix:'📱 Pix',dinheiro:'💵 Dinheiro',cartao:'💳 Cartão'};
 const items=cart.map(x=>{
  if(x.type=='drink')return `*${x.qty}-🥤 ${x.name}*`;
  const title=`*${x.qty}-${x.type=='combo'?'Combo Pizza ':''}${sizeNames[x.size]}*`;
  const details=[...x.flavors];
  if(x.border)details.push('*Borda:* '+x.border);
  (x.extras||[]).forEach(i=>details.push('*Adicional:* '+fillings[i][0]+(fillings[i][1]?' — '+fillings[i][1]:'')));
  if(x.drink)details.push('🥤 '+x.drink);
  if(x.type=='combo')details.push('Entrega inclusa');
  return title+'\n\n'+details.join('\n');
 });
 const customer=`*Cliente:* ${initial(checkout.name)}\n*Telefone:* ${checkout.phone.trim()}\n${checkout.mode=='entrega'?'*Endereço:* '+initial(checkout.address):'Retirada no balcão'}`;
 const change=checkout.payment=='dinheiro'&&checkout.change.trim()?'\n*Troco para:* R$ '+checkout.change.trim():'';
 const delivery=checkout.mode=='entrega'?'\n*Taxa de entrega:* '+(t.included?'Inclusa no combo':money(t.fee)):'';
 return `📝 *Novo pedido — Santi Pizza*\n\n${customer}\n\n*Pagamento:* ${payment[checkout.payment]}${change}\n\n${items.join('\n\n')}${checkout.note.trim()?'\n\n❗ *Recado:*\n'+initial(checkout.note):''}\n\n----------------------------------\n*Subtotal:* ${money(t.subtotal)}${delivery}\n*Total:* ${money(t.total)}`;
}
function send(){if(!cart.length)return alert('Adicione algum item ao pedido.');if(!checkout.name.trim()||!checkout.phone.trim()||(checkout.mode=='entrega'&&!checkout.address.trim()))return alert('Preencha nome, telefone e endereço para entrega.');const message=orderMessage();window.open('https://wa.me/'+WHATSAPP+'?text='+encodeURIComponent(message),'_blank','noopener');cart=[];checkout.note='';render();}
document.getElementById('open-cart-top').onclick=document.getElementById('open-cart').onclick=()=>openModal('cart','<div class="cart-content">'+ticket(totals())+'</div>');
overlay.addEventListener('click',e=>{if(e.target==overlay)closeModal()});
document.addEventListener('keydown',e=>{if(!modalType)return;if(e.key=='Escape')closeModal();if(e.key=='Tab'){const nodes=[...overlay.querySelectorAll('button:not(:disabled),input,select,textarea,[tabindex="0"]')],first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement==first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement==last){e.preventDefault();first.focus()}}});
restoreCart();
render();
